### ISSUE TITLE
Update ROS/Gazebo tutorial mentioning the appropriate version of Gazebo to use for new ROS/ROS2 distros

### ISSUE THREAD

**Issue by traversaro** [osrf/gazebo_tutorials#127]
The tutorial in http://gazebosim.org/tutorials/?tut=ros_wrapper_versions is missing the info for the following distros: 
* ROS1 Noetic 
* ROS2 Foxy

**Comment by traversaro** [comment]
I think I can't add labels, but this is probably a `good first issue` .

**Comment by Jidnyasa-git** [comment]
Hi, I want to work on this issue. Can you assign it to me ?

**Comment by chapulina** [comment]
> Hi, I want to work on this issue. Can you assign it to me ?

Great! Done!

**Comment by Jidnyasa-git** [comment]
I opened a PR. Please review it.

**Comment by chapulina** [comment]
Done in #128 , thanks!

**Comment by traversaro** [comment]
Thanks a lot @Jidnyasa-git !

**Comment by Jidnyasa-git** [comment]
This was my first PR. I learnt a lot. Grateful for this opportunity.
