### ISSUE TITLE
Windows installation fails during configure gazebo step with recent CMake versions

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo_tutorials#52]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo_tutorials-gh-pages/#!/osrf/gazebo_tutorials/issues/52)) by Jens Fischer (Bitbucket: [Gama11](https://bitbucket.org/%7B4465c4fd-8cef-47b1-aa70-df2453ad7d59%7D/)).**

----------------------------------------
When following the install instructions on http://gazebosim.org/tutorials?tut=install_on_windows&cat=install#Installation, everything went fine until I got to the `..\configure` step for gazebo itself. It failed with:

```
-- Could NOT find PROTOBUF (missing: PROTOBUF_LIBRARY) 
```

I eventually downgraded from CMake 3.5.1 to 3.4.3, and then again to 3.2.0 because that still didn't work. With 3.2.0, the CMake step was successful (still having some issues with compilation, but that's a separate issue).

**Comment by j-rivero** [comment]
The documentation and artifacts to compile on Windows are outdated. Instead of fixing the current mess, let's try to find a better approach, we'll appreciate your experience and opinions on the alternatives proposed and linked in https://github.com/osrf/gazebo/issues/2901. Thanks.
