### ISSUE TITLE
Windows install tutorial shouldn't be using default branches

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo_tutorials#82]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo_tutorials-gh-pages/#!/osrf/gazebo_tutorials/issues/82)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
One solution would be to lock the current tutorial to gazebo8 and make a new tutorial for gazebo9.

See more detailed discussion on [pull request #459](https://osrf-migration.github.io/gazebo_tutorials-gh-pages/#!/osrf/gazebo_tutorials/pull-requests/459).

**Comment by j-rivero** [comment]
Follow in https://github.com/osrf/gazebo/issues/2901
