### ISSUE TITLE
Remove or update Windows installation tutorial

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo_tutorials#92]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo_tutorials-gh-pages/#!/osrf/gazebo_tutorials/issues/92)) by Silvio Traversaro (Bitbucket: [traversaro](https://bitbucket.org/%7B34f404cb-5642-4f27-a032-e04c7143d776%7D/)).**

----------------------------------------
The Windows installation tutorial at [http://gazebosim.org/tutorials?tut=install\_on\_windows&cat=install](http://gazebosim.org/tutorials?tut=install_on_windows&cat=install) is quite outdated, and can be confusing for users \(see [https://www.reddit.com/r/ROS/comments/btnndg/dead\_link\_for\_gazebo\_dependencies/](https://www.reddit.com/r/ROS/comments/btnndg/dead_link_for_gazebo_dependencies/)\). 

Even if the binary distributed by ROSOnWindows’ Chocolatey may still not be perfect, perhaps it could make sense to change this tutorial to explain how to install Gazebo through those? 

‌

cc @seanyen-msft

**Comment by j-rivero** [comment]
Follow in https://github.com/osrf/gazebo/issues/2901
