### ISSUE TITLE
Error installing Gazebo on Windows following the tutorial

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gazebo_tutorials#96]
**Original report ([archived issue](https://osrf-migration.github.io/gazebo_tutorials-gh-pages/#!/osrf/gazebo_tutorials/issues/96)) by Simone Enomis (Bitbucket: [Simone Enomis](https://bitbucket.org/%7B4522d485-3806-4ca7-b058-d4e7356e3d02%7D/)).**

----------------------------------------
Hi everybody, I am trying to follow the tutorial to install **Gazebo 11** on Windows 10 build 1903.

First and formost some dependency links are broken, however I figured out how to find those files on the Internet: they are `protobuf 3.4.1` and `zlib`.

Morever, I experienced several errors in **step 8**. When executing `configure.bat` I got the error reported below.  
In particular, the system isn't able to find the labels `:download_unzip_install` and `:install_ign_project ign-cmake`, referred in the batch extract:

```
:: Install dependencies

call %win_lib% :download_unzip_install eigen3-3.3.4.zip

call %win_lib% :install_ign_project ign-cmake ign-cmake2
```

> **Note**: `win_lib` on my PC is empty.

Please, can somebody help me? Thanks in advance.

**Details of the command execution:**

```
C:\Users\Asus\gz-ws\ign-math>configure Debug

C:\Users\Asus\gz-ws\ign-math>call  :download_unzip_install eigen3-3.3.4.zip
Impossibile trovare l'etichetta batch specificata - download_unzip_install

C:\Users\Asus\gz-ws\ign-math>call  :install_ign_project ign-cmake ign-cmake2
Impossibile trovare l'etichetta batch specificata - install_ign_project
```

‌

**Comment by shadowzone22** [comment]
got the same problem here , details of execution 

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.6.2
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************

C:\Windows\System32>d:

D:\>cd ign-fuel-tools
The system cannot find the path specified.

D:\>cd gz-ws

D:\gz-ws>cd ign-fuel-tools

D:\gz-ws\ign-fuel-tools>.\configure

D:\gz-ws\ign-fuel-tools>call  :download_unzip_install curl-7.57.0-vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

D:\gz-ws\ign-fuel-tools>call  :download_unzip_install jsoncpp-1.8.4-vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

D:\gz-ws\ign-fuel-tools>call  :download_unzip_install libyaml-0.1.7-vc15-x64-md.zip
The system cannot find the batch label specified - download_unzip_install

D:\gz-ws\ign-fuel-tools>call  :download_unzip_install libzip-1.4.0_zlip-1.2.11_vc15-x64-dll-MD.zip
The system cannot find the batch label specified - download_unzip_install

D:\gz-ws\ign-fuel-tools>call  :install_ign_project ign-common ign-common1
The system cannot find the batch label specified - install_ign_project
Configuring for build type Release

D:\gz-ws\ign-fuel-tools>cd /d D:\gz-ws\ign-fuel-tools\

D:\gz-ws\ign-fuel-tools>md build
A subdirectory or file build already exists.

D:\gz-ws\ign-fuel-tools>cd build

D:\gz-ws\ign-fuel-tools\build>cmake .. -G "NMake Makefiles" -DCMAKE_INSTALL_PREFIX="" -DCMAKE_BUILD_TYPE="Release" -DBUILD_TESTING:BOOL=False
-- ignition-fuel_tools1 version 1.2.0
-- Operating system is Windows
-- Looking for IgnCURL - found

-- Checking for module 'jsoncpp'
--   No package 'jsoncpp' found
-- Could NOT find JSONCPP (missing: JSONCPP_FOUND)
-- Attempting manual search for jsoncpp
-- Looking for jsoncpp headers - not found
-- Looking for jsoncpp library - not found
-- Could NOT find JSONCPP (missing: JSONCPP_FOUND)
-- Looking for JSONCPP - not found

-- Checking for module 'yaml-0.1'
--   No package 'yaml-0.1' found
-- Could NOT find YAML (missing: YAML_FOUND)
-- Attempting manual search for yaml
-- Looking for yaml headers - not found
-- Looking for yaml library - not found
-- Could NOT find YAML (missing: YAML_FOUND)
-- Looking for YAML - not found

-- Checking for module 'libzip'
--   No package 'libzip' found
-- Could NOT find ZIP (missing: ZIP_FOUND)
-- Attempting manual search for zip
-- Looking for zip headers - not found
-- Looking for zip library - not found
-- Could NOT find ZIP (missing: ZIP_FOUND)
-- Looking for ZIP - not found

CMake Warning at C:/opt/rosdeps/x64/lib/cmake/ignition-cmake0/cmake0/IgnUtils.cmake:146 (find_package):
  By not providing "Findignition-common1.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-common1", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-common1"
  (requested version 1.1.0) with any of the following names:

    ignition-common1Config.cmake
    ignition-common1-config.cmake

  Add the installation prefix of "ignition-common1" to CMAKE_PREFIX_PATH or
  set "ignition-common1_DIR" to a directory containing one of the above
  files.  If "ignition-common1" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:47 (ign_find_package)


-- Looking for ignition-common1 - not found

CMake Warning (dev) at C:/opt/rosdeps/x64/lib/cmake/ignition-cmake0/cmake0/IgnUtils.cmake:265 (message):
   -- THIS MESSAGE IS INTENDED FOR IGNITION-FUEL_TOOLS AUTHORS --
      (IF YOU SEE THIS, PLEASE REPORT IT)

  Could not find pkg-config information for ignition-common1.  It was not
  provided by the find-module for the package, nor was it explicitly passed
  into the call to ign_find_package(~).  This is most likely an error in this
  project's use of ign-cmake.
Call Stack (most recent call first):
  CMakeLists.txt:47 (ign_find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for ignition-tools - found

-- BUILD ERRORS: These must be resolved before compiling.
--      Missing: JSONCPP
--      Missing: YAML
--      Missing: ZIP
--      Missing: ignition-common1
--  END BUILD ERRORS

CMake Error at C:/opt/rosdeps/x64/lib/cmake/ignition-cmake0/cmake0/IgnConfigureBuild.cmake:64 (message):
  Errors encountered in build.  Please see BUILD ERRORS above.
Call Stack (most recent call first):
  CMakeLists.txt:60 (ign_configure_build)


-- Configuring incomplete, errors occurred!
See also "D:/gz-ws/ign-fuel-tools/build/CMakeFiles/CMakeOutput.log".
D:\gz-ws\ign-fuel-tools\build>

**Comment by spygibas** [comment]
Found Solution now, I suggest you use  cmake-gui.exe ,you will find at C:\Program Files\CMake\bin if you install on that directory
1. run cmake-gui.exe
2. select  path source code and select path to build
3. run configure 1 time you will found error same
4. edit path ignition-cmake0_DIR to gz-ws/ign-cmake/build/install/Release/lib/cmake/ignition-cmake0 
5. Run again Done !!

**Comment by jonyktan** [comment]
Adding on to above, for step 10, faced the same errors, and

...
-- Configuring incomplete, errors occurred!
See also "C:/.../gz-ws/ign-common/build/CMakeFiles/CMakeOutput.log".
C:\...\gz-ws\ign-common\build>nmake

Microsoft (R) Program Maintenance Utility Version 14.16.27043.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.

Help would be greatly appreciated please. Thank you!

**Comment by kwint** [comment]
Same problem here!
Where should `download_unzip_install` be located? 

And other wise, how can we install the dependencies manually?

**Comment by kwint** [comment]
So I got a little bit further, but not much. I found this jenkins CI script that tests ignition_cmake build: https://build.osrfoundation.org/job/ignition_cmake-ci-default-windows7-amd64/lastBuild/consoleText

I found that the download_unzip_install script is found here:
`git clone https://github.com/ignition-tooling/release-tools scripts -b master`
And that you have to set the env var `%win_lib%` to this file: https://github.com/ignition-tooling/release-tools/blob/master/jenkins-scripts/lib/windows_library.bat

Then configure.dat can call download_unzip_install. What it does is it downloads some ignition packages again, which  you have already done by instructions from the tutorial, installs them in you C:\ drive and then it fails again with the same error. 
By setting the env var `WORKSPACE_INSTALL_DIR` to  `..\gz_ws\install\` I got a little bit further.

But thats all that I have time for. All the scripts in here are used mainly for CI, the configure.dat even has two lines in it saying that it should only be used for CI. 

We could really use a good update on this tutorial!!

**Comment by chapulina** [comment]
Just cross-referencing a couple of open pull requests related to this: #101 / #97

**Comment by AnjanaWijesinghe** [comment]
I managed to complete .\configure after manually editing the CMakeCache with the directories and paths to the extracted jsoncpp, yaml and zip folders and the .lib files within it (it also mentions a ignition-tools, which I wasn't able to find although this just gave a warning and not an error).
Now I'm stuck in the next step of nmake, which says:
`cl : Command line warning D9025 : overriding '/W3' with '/W2'
ClientConfig.cc
E:\gz-ws\ign-fuel-tools\src\ClientConfig.cc(18): fatal error C1083: Cannot open include file: 'yaml.h': No such file or directory
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx86\x64\cl.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\nmake.exe"' : return code '0x2'
Stop.`

I'm trying to figure out whether this means yaml needs to be installed (should it?) or needs to be configured some other way which I'm not aware of? Or have I done something wrong when I edited the CMakeCache file?

**Comment by AnjanaWijesinghe** [comment]
I did get nmake to work by replacing the `include<yaml.h>` with `include<E:/gz-ws/libyaml-0.1.7-vc15-x64-md/include/yaml.h>`. 
I also did the same to json and zip when the errors occurred. nmake did work for now, I'll have to finish the whole setup to figure out if this actually works or not.

**Comment by hectormdom** [comment]
> I managed to complete .\configure after manually editing the CMakeCache with the directories and paths to the extracted jsoncpp, yaml and zip folders and the .lib files within it (it also mentions a ignition-tools, which I wasn't able to find although this just gave a warning and not an error).
> Now I'm stuck in the next step of nmake, which says:
> `cl : Command line warning D9025 : overriding '/W3' with '/W2' ClientConfig.cc E:\gz-ws\ign-fuel-tools\src\ClientConfig.cc(18): fatal error C1083: Cannot open include file: 'yaml.h': No such file or directory NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx86\x64\cl.exe"' : return code '0x2' Stop. NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\nmake.exe"' : return code '0x2' Stop. NMAKE : fatal error U1077: '"D:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\nmake.exe"' : return code '0x2' Stop.`
> 
> I'm trying to figure out whether this means yaml needs to be installed (should it?) or needs to be configured some other way which I'm not aware of? Or have I done something wrong when I edited the CMakeCache file?

Hi, is there any chance you could share the changes you made to the CMakeCache? I'm trying to manually set the paths up, however .\configure still complains that it isn't finding the required files.

**Comment by AnjanaWijesinghe** [comment]
I did not manage to get Gazebo working properly. I opted into running it on a VM with Ubuntu instead which wasn't ideal because Gazebo is somewhat resource heavy to run on a VM (my laptop isn't high-end either). Therefore, finally got Ubuntu dual booted and got Gazebo running there.

**Comment by hectormdom** [comment]
> I did not manage to get Gazebo working properly. I opted into running it on a VM with Ubuntu instead which wasn't ideal because Gazebo is somewhat resource heavy to run on a VM (my laptop isn't high-end either). Therefore, finally got Ubuntu dual booted and got Gazebo running there.

Thanks for your reply, that was exactly what I was thinking as a next step :(

**Comment by AnjanaWijesinghe** [comment]
> > I did not manage to get Gazebo working properly. I opted into running it on a VM with Ubuntu instead which wasn't ideal because Gazebo is somewhat resource heavy to run on a VM (my laptop isn't high-end either). Therefore, finally got Ubuntu dual booted and got Gazebo running there.
> 
> Thanks for your reply, that was exactly what I was thinking as a next step :(

Running it on Ubuntu is a breeze, one command and it works like a charm.

**Comment by j-rivero** [comment]
The documentation and artifacts to compile on Windows are outdated. Instead of fixing the current mess, let's try to find a better approach, we'll appreciate your experience and opinions on the alternatives proposed and linked in https://github.com/osrf/gazebo/issues/2901. Thanks.
